version : "3"
services:
#mongo:
#  image: mongo
#  ports:
#    - "27017:27017"
#  container_name: mongo
#  network_mode: host

  config-server:
    image: configservice-app
    build: config-server/
    restart: always
    network_mode: host
    container_name: config-server-docker
    ports:
      - "8066:8066"
    expose:
      - 8066

  eureka-service:
    image: eurekaservice-app
    build: eureka-service/
    restart: always
    network_mode: host
    container_name: eureka-service-docker
    ports:
      - "9091:9091"
    expose:
      - 9091

  track-service:
    image: trackservice-app
    build: TrackService/
    restart: always
    network_mode: host
    hostname: localhost
    container_name: track-service-docker
    depends_on:
      - config-server
      - eureka-service

    ports:
      - "8088:8088"
    expose:
      - 8088

  userservice:
    image: userservice-app
    build: UserService/
    restart: always
    network_mode: host
    container_name: user-service-docker
    depends_on:
      - config-server
      - eureka-service
    ports:
      - "8193:8193"
    expose:
      - 8193

  zuul-service:
    image: zuul-service-app
    build: zuul-service/
    restart: always
    network_mode: host
    container_name: zuul-service-docker
    ports:
      - "8085:8085"
    expose:
      - 8085

